version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build Project
          command: |
            ./gradlew build
      - run:
          name: Run Unit Tests
          command: |
            ./gradlew test
  api_test:
    docker:
      - image: circleci/openjdk:11
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run API Tests
          command: |
            ./gradlew test --tests ApiTest
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - api_test:
          requires:
            - build
